on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version : major, minor, patch'     
        required: true
        options: ['major', 'minor', 'patch']
        default: 'minor'
name: Generate Dev Version 
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      GITHUB_TOKEN: s{{secrets.REPOSITORY_TOKEN}}
      NODE_VERSION: 'v14.15.4'
      VERSION_TYPE:
      VERSION_TAG:
    steps:
      - run: |
          echo "${{ github.event.inputs.version }}"
          echo "::set-env name=VERSION_TYPE::${{ github.event.inputs.version }}"
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup nodejs ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install and npm build
        run: |
          npm ci
          npm run build
      - name: Generate new ${{ env.VERSION_TYPE}} version 
        run: |
          npm --no-git-tag-version version ${{ env.VERSION_TYPE}}
      - name: Read new Package Json
        id: set_var
        run: |
          content=`cat package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: update runner env
        run: |
          echo "::set-env name=VERSION_TAG::dev_${{fromJson(steps.set_var.outputs.packageJson).version}}"
      - name: Commit files
        run: |
          git config  user.email "diegopatino@doprr.com"
          git config  user.name "Diego Patino"
          git add .
          git commit -m "Generate Dev Version ${{ env.VERSION_TAG }}"
          git push
      
      - name: Tag Dev Version ${{ env.VERSION_TAG }}
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ env.VERSION_TAG }}"

         

#